import{a as q,S as w,i}from"./assets/vendor-BAQQTdrx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();async function m(e,r=1){return(await q.get("https://pixabay.com/api/",{params:{key:"55690336-89d3439cb4fd8c4c20b1d93a7",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const v=new w(".gallery a",{captionsData:"alt",captionDelay:250});function f(e){const r=document.querySelector(".gallery"),s=e.map(({webformatURL:a,largeImageURL:t,tags:o,likes:n,views:b,comments:L,downloads:S})=>`<li class="gallery-item">
  <a href='${t}'>
    <img class="gallery-image" src='${a}' alt ='${o}'>    
  </a>
  <div class="info">
  <p><span class="label">Likes:</span> ${n}</p>
  <p><span class="label">Views:</span> ${b}</p>
  <p><span class="label">Comments:</span> ${L}</p>
  <p><span class="label">Downloads:</span> ${S}</p>
</div>
</li>`).join("");r.insertAdjacentHTML("beforeend",s),v.refresh()}function M(){document.querySelector(".gallery").innerHTML=""}function g(){const e=document.querySelector(".loader");e&&e.classList.remove("is-hidden")}function y(){const e=document.querySelector(".loader");e&&e.classList.add("is-hidden")}function h(){const e=document.querySelector(".load-more-btn");e&&e.classList.remove("is-hidden")}function u(){const e=document.querySelector(".load-more-btn");e&&e.classList.add("is-hidden")}const p=document.querySelector(".form"),P=document.querySelector(".load-more-btn");let c="",l=1,d=0;p.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.currentTarget.elements["search-text"].value.trim(),c===""){i.error({message:"Please enter a search term",position:"topRight"});return}l=1,M(),g(),u();try{const r=await m(c,l);if(d=r.totalHits,r.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}f(r.hits),p.reset(),d>15&&h()}catch(r){console.log(r),i.error({message:"Something went wrong!",position:"topRight"})}finally{y()}});P.addEventListener("click",async()=>{l+=1,u(),g();try{const e=await m(c,l);d=e.totalHits,f(e.hits);const r=document.querySelector(".gallery-item");if(r){const{height:a}=r.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}const s=Math.ceil(d/15);l>=s?(u(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):h()}catch(e){console.log(e),i.error({message:"Error loading more images"})}finally{y()}});
//# sourceMappingURL=index.js.map
